FROM golang:1.26-alpine

WORKDIR /app

# Install git for go mod and air for hot-reload
RUN apk add --no-cache git
RUN go install github.com/air-verse/air@latest

# Copy go mod and sum files first for caching
COPY go.mod go.sum ./
RUN go mod download

# Copy the rest of the code
COPY . .

# Expose API port
EXPOSE 8080

# Run air for hot-reload
CMD ["air", "-c", ".air.toml"]
